In [2]:
import numpy as np 

In [6]:
import numpy as np

inputArray = np.array([
    [1, 2, 3],
    [4, 5, 6]  
])


In [7]:
print(inputArray)

[[1 2 3]
 [4 5 6]]


In [17]:
inputArray.shape

(2, 3)

In [8]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Performing all the operations 

In [9]:
result = A + B
print("Addition:\n", result)

Addition:
 [[ 6  8]
 [10 12]]


In [10]:
result = A - B
print("Subtraction:\n", result)

Subtraction:
 [[-4 -4]
 [-4 -4]]


In [11]:
result = A @ B  # Or use np.dot(A, B)
print("Matrix Multiplication:\n", result)


Matrix Multiplication:
 [[19 22]
 [43 50]]


In [12]:
result = A * B
print("Element-wise Multiplication:\n", result)


Element-wise Multiplication:
 [[ 5 12]
 [21 32]]


In [13]:
result = A / B
print("Division:\n", result)


Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [14]:
print("Transpose of A:\n", A.T)


Transpose of A:
 [[1 3]
 [2 4]]


In [15]:
print("Sum:", np.sum(A))
print("Mean:", np.mean(A))
print("Max:", np.max(A))
print("Min:", np.min(A))


Sum: 10
Mean: 2.5
Max: 4
Min: 1


In [16]:
print("Square root:\n", np.sqrt(A))
print("A squared:\n", np.power(A, 2))


Square root:
 [[1.         1.41421356]
 [1.73205081 2.        ]]
A squared:
 [[ 1  4]
 [ 9 16]]
